services:
  db:
    container_name: digital_wallet_db
    image: postgres:16
    env_file: ".env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
volumes:
  postgres: