CREATE TABLE users(
    id UUID NOT NULL PRIMARY KEY,
    email VARCHAR(70) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    tax_number VARCHAR(15) NOT NULL UNIQUE,
    full_name VARCHAR(70) NOT NULL,
    type VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE  NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE
);