CREATE TABLE Users(
    Id UUID NOT NULL PRIMARY KEY,
    Email VARCHAR(70) NOT NULL UNIQUE,
    Password VARCHAR(50) NOT NULL,
    TaxNumber VARCHAR(15) NOT NULL UNIQUE,
    FullName VARCHAR(70) NOT NULL,
    Type VARCHAR(30) NOT NULL,
    CreateAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UpdateAt DATETIME
);